### ISSUE TITLE
How to get the data of ch2 and ch3?

### ISSUE THREAD

**Issue by Marida-Cruz** [zharijs/FDC2214#2]
I appreciate your uploading the library of FDC2214.
This is very nice and we can make some interesting gadgets with FDC2214 and your library.

I am sorry, but I have a small question.
How to get the data of ch2 and ch3?
I changed two parts as;
(1)"capsense.begin(0xF, 0x4, 0x5)"
(2)"#define CHAN_COUNT 4 "

But the value of ch1, ch2 and ch3 show same value.
////////////////////
FDC2x1x test
Sensor OK
15500397, 15085240, 15085240, 15085240
15502770, 15085022, 15085022, 15085022
15503196, 15084950, 15084950, 15084950
15503481, 15084928, 15084928, 15084928
15503504, 15084836, 15084836, 15084836
15503656, 15084807, 15084807, 15084807
////////////////////
Is there any method to get data of ch2 and ch3 ?

**Comment by zharijs** [comment]
Hi Marida,
I had only FDC2212 to work with. I'll put some 2214 board together and fix the lib in couple of days.

**Comment by zharijs** [comment]
@Marida-Cruz - grab the new v1.1.
I've put the test board for 4 chan chip together and fixed the code - you can use it for 4 chan operation out of the box now. 
have fun.

**Comment by Marida-Cruz** [comment]
Dear, Mr./Ms. zharijs

Thank you very much for the reply.
Now I can use it for 4 chan.

I'm sorry to bother you.
And thank you very much.
