### ISSUE TITLE
Using with FDC2112, 1st channel transmits only 0x40000, 0x30000 and 0x20000

### ISSUE THREAD

**Issue by AndreiMiculita** [zharijs/FDC2214#8]
Hello!

Has anyone tested this on the FDC2112?

I've connected FDC2112 to an Arduino as follows:

```
Arduino | Level shifter | FDC2112
5V   ---| HV        LV  |--- 3.3V
3.3V ---|---------------|-'
GND  ---| GND      GND  |--- GND
A4   ---| HV1      LV1  |--- SDA
A5   ---| HV2      LV2  |--- SCL
```

I've run `testFDC-Serial.ino`:
https://github.com/zharijs/FDC2214/blob/8dc23684ccbd1629eeb41d2a0e99316ff1611503/examples/testFDC-Serial/testFDC-Serial.ino#L48-L68

 with the following modifications:

Uncomment https://github.com/zharijs/FDC2214/blob/8dc23684ccbd1629eeb41d2a0e99316ff1611503/examples/testFDC-Serial/testFDC-Serial.ino#L48
Comment out  https://github.com/zharijs/FDC2214/blob/8dc23684ccbd1629eeb41d2a0e99316ff1611503/examples/testFDC-Serial/testFDC-Serial.ino#L50
Change 4 to 2 https://github.com/zharijs/FDC2214/blob/8dc23684ccbd1629eeb41d2a0e99316ff1611503/examples/testFDC-Serial/testFDC-Serial.ino#L59
Change 28 to 16 https://github.com/zharijs/FDC2214/blob/8dc23684ccbd1629eeb41d2a0e99316ff1611503/examples/testFDC-Serial/testFDC-Serial.ino#L66
Add HEX argument to print to see what's happening more clearly: https://github.com/zharijs/FDC2214/blob/8dc23684ccbd1629eeb41d2a0e99316ff1611503/examples/testFDC-Serial/testFDC-Serial.ino#L68

This results in the 2 channels only ever transmitting 0s. Setting `intOsc` to true on line 48 results in channel 0 transmitting 40000 , 30000, or 20000 (I am using [this](https://www.mikroe.com/moisture-click) skin capacitance sensor  ([schematic](https://download.mikroe.com/documents/add-on-boards/click/moisture/moisture-click-schematic-v100.pdf))).

This is obviously a very low resolution, much less than the advertised 12 bits. I've tried changing the MSB address, but unfortunately all values between 0x00-0x07 are just FFFs (i.e. channel 0 transmits FFF0000 for FDC2214_DATA_CH0_MSB being set to any of 0x00-0x07).

**Comment by AndreiMiculita** [comment]
Update: after having a good look at the datasheet, a solution is to change the gain flag to 0b11:

```cpp
// Set the gain flag of the moisture sensor
    uint16_t gainFlag = capsense.read16FDC(0x1C);
    Serial.println(gainFlag, HEX);
    capsense.write16FDC(0x1C, 0x3 << 9);
    gainFlag = capsense.read16FDC(0x1C);
    Serial.println(gainFlag, HEX);
```

This results in a 6-bit resolution, which was good enough for my application. This only applies to the FDC2112 and FDC2114.

**Comment by hussain01w** [comment]
have you used moisture click that uses FDC2112 if yes please send me the full code you used to integrate FDC 2112
